name: build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Prepare
        run: |
          echo "date=$(date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: meow-accounts-mobile-${{ env.date }}
          path: dist

      - name: Package Version Updated
        uses: MontyD/package-json-updated-action@1.0.1
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tar
        if: steps.version-updated.outputs.has-updated
        run: |
          cd dist
          tar -zcvf meow-accounts-mobile-${{ steps.version-updated.outputs.current-package-version }}.tar.gz *

      - name: Release
        uses: ncipollo/release-action@v1
        if: steps.version-updated.outputs.has-updated
        with:
          name: ${{ steps.version-updated.outputs.version }}
          tag: ${{ env.date }}
          token: ${{ secrets.ADMIN }}
          artifacts: "dist/meow-accounts-mobile-${{ steps.version-updated.outputs.current-package-version }}.tar.gz"
