name: build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Prepare
        run: |
          echo "date=$(date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: meow-accounts-mobile-${{ env.date }}
          path: dist

      - name: CheckVersion
        uses: johnnybenson/package-json-versioned-action@v1.0.1
        id: version-updated
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_JSON_PATH: package.json

      - run: echo "has-updated -- ${{ steps.version-updated.outputs.has-updated }}"
      - run: echo "version -- ${{ steps.version-updated.outputs.version }}"
      - run: echo "has-updated-str -- ${{ steps.version-updated.outputs.has-updated == true }}"
      - run: echo "has-updated-str1 -- ${{ steps.version-updated.outputs.has-updated == false }}"

      - name: Tar
        if: steps.version-updated.outputs.has-updated == true
        run: |
          cd dist
          tar -zcvf meow-accounts-mobile-${{ steps.version-updated.outputs.version }}.tar.gz *

      - name: Release
        uses: ncipollo/release-action@v1
        if: steps.version-updated.outputs.has-updated == true
        with:
          name: ${{ steps.version-updated.outputs.version }}
          tag: ${{ env.date }}
          token: ${{ secrets.ADMIN }}
          artifacts: "dist/meow-accounts-mobile-${{ steps.version-updated.outputs.version }}.tar.gz"
