name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Prepare
        run: |
          echo "date=$(date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV

      - uses: copapow/version-bump-package@v1
        with:
          default_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: "Bump package version"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Tar
        run: |
          cd dist
          tar -zcvf meow-accounts-mobile-${{ steps.bump.outputs.new_version }}.tar.gz *

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.bump.outputs.new_version }}
          tag: ${{ env.date }}
          token: ${{ secrets.REPO_TOKEN }}
          artifacts: "dist/meow-accounts-mobile-${{ steps.bump.outputs.new_version }}.tar.gz"
